export const SHOW_HIDE_CART = "SHOW_HIDE_CART";
export const ADD_TO_CART = "ADD_TO_CART";
export const INCREMENT_ITEM = "INCREMENT_ITEM"
export const DECREMENT_ITEM = "DECREMENT_ITEM"
export const UPDATE_TOTAL = "UPDATE_TOTAL"
export const REALIZAR_VENTA = "REALIZAR_VENTA"


export const IS_ADMIN = "IS_ADMIN";